### ISSUE TITLE
Remove branches no longer needed

### ISSUE THREAD

**Issue by mcmahonjohn** [aarontitus/crisiscleanup#283]
I notice there are quite a few branches that have already been merged or closed. Can these be safely deleted? It would help reduce size of the repo for contributors and they can focus on looking on the branches in progress.

**Comment by aarontitus** [comment]
First of all, thanks for your interest. I assume so, but to be honest, I don't know whether they can be safely deleted. The code base was under active development and came to a sudden mid-stream stop when funding unexpectedly ran out. So I'm not sure exactly what all can be deleted.

**Comment by mcmahonjohn** [comment]
Hmm..okay. Just looked at the comparison between the branches that were merged and master.

They are all ~250 commits **behind** master (ie: commits in master these branches do not have).

And none are listed as **ahead** of master (ie: commits in the branches that *master* does not have).

So I think its safe to remove the Merged branches.

I just heard the FLOSS Weekly podcast that had featured this project. So I wanted to check it out. I'm a newbie in Ruby. Mostly do web development via AngularJS, HTML/JS. So I'll likely look around for anything I can do.

**Comment by aarontitus** [comment]
That's because development suddenly stopped mid-stream. All 250 commits ahead of those are minor tweaks on HTML. Due to lack of funding, there is no current development going on, but there was a lot going on before it had to stop. I don't want to jettison all of that work, in case we are ever able to fund some additional development in the future.
Welcome to Ruby :-)

**Comment by mcmahonjohn** [comment]
Okay, I'll close the ticket.
